/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        //Sending part of the tutorial
        // Send.SendHelloWorld();

        //Recieeving part of the tutorial
        // Recv.recieve();
        System.out.println("Hello World!");
    }
}
